AIRLINE_NAMES = {
    "AMERICAN AIRLINES, INC." : "American Airlines",
    "" : "Abaeté Aviação",
    "AIR CANADA" : "Air Canada",
    "AEROFLOT- AEROLÍNEAS INTERNACIONAIS DA RÚSSIA" : "Aeroflot",
    "SOCIÉTÉ AIR FRANCE" : "Air France",
    "ALAS DE VENEZUELA" : "Alas de Venezuela",
    "AEROVÍAS DE MÉXICO S.A DE C.V - AEROMÉXICO" : "Aeromexico",
    "AEROLINEAS ARGENTINAS S/A" : "Aerolíneas Argentinas",
    "AEROVIAS DEL CONTINENTE AMERICANO S.A. AVIANCA" : "Avianca Colômbia",
    "ALITALIA SOCIETA AEREA ITALIANA S.P.A." : "Alitalia",
    "BRITISH AIRWAYS PLC" : "British Airways",
    "TAM-TRANSPORTE AEREOS MERIDIONAIS" : "Transportes Aéreos Meridionais",
    "CANADIAN" : "Canadian",
    "KALITTA AIR LLC" : "Kalitta Air",
    "COMPAÑIA PANAMEÑA DE AVIACION S.A. (COPA AIRLINES)" : "Copa Airlines",
    "CONTINENTAL AIRLINES" : "Continental",
    "CROSSAIR LTD" : "Crossair",
    "CUBANA DE AVIACION S.A." : "Cubana",
    "CENTURION AIR CARGO INC." : "Centurion Air Cargo",
    "DELTA AIR LINES INC." : "Delta",
    "DEUTSCHE LUFTHANSA A.G." : "Lufthansa",
    "TAAG LINHAS AÉREAS DA ANGOLA (ANGOLA AIRLINES)" : "TAAG",
    "ECUATORIANA DE AVIACION S/A" : "Ecuatoriana",
    "FEDEX - FEDERAL EXPRESS CORPORATION" : "Fedex",
    "IBÉRIA LINEAS AEREAS DE ESPAÑA SOCIEDAD ANONIMA OPERADORA" : "Iberia",
    "INTERBRASIL" : "Interbrasil",
    "JAPAN AIRLINES INTERNATIONAL COMPANY LIMITED" : "JAL",
    "SPANAIR" : "Spanair",
    "KOREAN AIR LINES CO. LTD." : "Korean",
    "KLM CIA. REAL HOLANDESA DE AVIAÇÃO" : "KLM",
    "LATAM AIRLINES GROUP (EX - LAN AIRLINES S/A)" : "LATAM Chile",
    "TRANSPORTE AÉREOS DEL MERCOSUR S.A. (TAM MERCOSUR)" : "LATAM Paraguay",
    "LLOYD AEREO BOLIVIANO" : "LAB Airlines",
    "META - MESQUITA TRANSPORTES AÉREOS LTDA." : "Meta Linhas Aéreas",
    "NORDESTE" : "Nordeste Linhas Aéreas",
    "POLAR AIR CARGO LLC. (EX - POLAR AIR CARGO WORLDWIDE INC.)" : "Polar Air Cargo",
    "PENTA" : "Pena Transportes Aéreos",
    "PASSAREDO TRANSPORTES AÉREOS S.A." : "Passaredo",
    "PANTANAL LINHAS AÉREAS S.A." : "Pantanal",
    "PLUNA LÍNEAS AÉREAS URUGUAYAS" : "Pluna",
    "ABAETÉ LINHAS AÉREAS LTDA" : "Abaeté Linhas Aéreas",
    "SOUTH AFRICAN AIRWAYS STATE OWNED COMPANY (SOC) LIMITED" : "South African",
    "SURINAM AIRWAYS LTD" : "Surinam Airways",
    "SWISS INTERNATIONAL AIR LINES LTD." : "Swiss",
    "TAM LINHAS AÉREAS S.A." : "LATAM Brasil",
    "TAP - TRANSPORTES AÉREOS PORTUGUESES S/A" : "TAP Air",
    "TRANSBRASIL" : "Transbrasil",
    "TRIP SERVIÇOS DE SUPORTE AÉREO S.A (EX. TRIP LINHAS AÉREAS)" : "TRIP",
    "AVIANCA PERU S.A (EX: TRANS AMERICAN AIRLINES S.A. - TACA PERU)" : "Avianca Perú",
    "TOTAL LINHAS AÉREAS S.A." : "Total Cargo",
    "UNITED AIRLINES, INC" : "United",
    "VARIG - VIAÇÃO AÉREA RIO-GRANDENSE" : "VARIG",
    "VIAÇÃO AÉREA SÃO PAULO" : "VASP",
    "CONDOR FLUGDIENST GMBH" : "Condor",
    "GOL LINHAS AÉREAS S.A. (EX- VRG LINHAS AÉREAS S.A.)" : "Gol",
    "ATLAS AIR INC" : "Atlas Air",
    "TRANSPORTE AÉREO SA - TASA (LAN EXPRESS)" : "LAN Express",
    "TAMPA CARGO S.A." : "Avianca Cargo",
    "UPS - UNITED PARCEL SERVICE CO." : "UPS",
    "VARIG LOGÍSTICA S.A." : "VARIG Log",
    "LAN PERU S.A." : "LATAM Peru",
    "ABSA - AEROLINHAS BRASILEIRAS S.A." : "LATAM Cargo",
    "OCEANAIR LINHAS AÉREAS S.A. (AVIANCA)" : "OceanAir",
    "AEROSUR - CIA BOLIVIANA DE TRANSPORTE AÉREO PRIVADO S.A." : "AeroSur",
    "AIR EUROPA LINEAS AEREAS SOCIEDAD ANONIMA" : "Air Europa",
    "CARGOLUX AIRLINES INTERNATIONAL S/A" : "Cargolux",
    "AEROTRANSPORTES MAS DE CARGA S.A. DE C.V." : "MasAir Cargo",
    "LUFTHANSA CARGO AG" : "Lufthansa Cargo",
    "AIR CARAIBES S.A." : "Air Caraíbes",
    "AIR EURO AMERICA" : "Air Euro America",
    "WEBJET PARTICIPAÇÕES S.A. (EX-LINHAS AÉREAS)" : "Webjet",
    "LAN CARGO S.A." : "LATAM Cargo Chile",
    "EMIRATES" : "Emirates",
    "VRG LINHAS AÉREAS S.A." : "VARIG",
    "AZUL LINHAS AÉREAS BRASILEIRAS S/A" : "Azul",
    "AIR CHINA" : "Air China",
    "LÍNEA AÉREA CARGUEIRA DE COLOMBIA S.A - LANCO" : "LANCO",
    "LAN EQUADOR" : "LAN Equador",
    "MARTINAIR HOLLAND N.V." : "Martinair",
    "TURKISH AIRLINES INC" : "Turkish Airlines",
    "US AIRWAIS, INC" : "US Airways",
    "BOA BOLIVIANA DE AVIACIÓN" : "BOA",
    "EL AL ISRAEL AIRLINES LTD" : "El Al Israel",
    "QATAR AIRWAYS" : "Qatar",
    "ARROW AIR, INC." : "Arrow Cargo",
    "CARGOLUX ITÁLIA S.P.A." : "Cargolux",
    "SINGAPORE AIRLINES LIMITED" : "Singapore",
    "ATA BRASIL" : "ATA Brasil",
    "ANTONOV AIRLINES" : "Antonov",
    "AUSTRAL LINEAS AÉREAS - CIELOS DEL SUR" : "Austral Lineas Aéreas",
    "HI FLY TRANSPORTES AEREOS" : "Hi Fli",
    "SKY LEASE I, INC" : "Sky Lease",
    "AVIANCA COSTA RICA SOCIEDAD ANONIMA ( EX - LACSA LÍNEAS AÉREAS COSTARRICENSES S/A)" : "LACSA Líneas Aéreas",
    "BRA" : "BRA Transportes Aéreos",
    "BRASMEX - BRASIL MINAS EXPRESS LTDA." : "Brasmex",
    "BRAVA LINHAS AÉREAS LTDA. (EX- NHT)" : "Brava Linhas Aéreas",
    "SIDERAL LINHAS AÉREAS LTDA." : "Sideral Linhas Aéreas",
    "SOUTHERN AIR INC" : "Southern Air",
    "SINGAPORE AIRLINES CARGO PTE LTD." : "Singapore Cargo",
    "TUI AIRLINES NEDERLAND BV" : "TUI Netherlands",
    "CIELOS DEL PERU" : "Cielos Cargo",
    "VOLGA DNEPR AIRLINES" : "Volga Dnepr",
    "CONNECT LINHAS AÉREAS S.A. (ANTIGA CONNECT TÁXI AÉREO LTDA.)" : "Connect Cargo",
    "BQB LÍNEAS AÉREAS (LOS CIPRESES S.A.)" : "BQB Lineas Aéreas",
    "EDELWEISS AIR AG" : "Edelweiss",
    "ETIHAD AIRWAYS P.J.S.C." : "Etihad",
    "ETHIOPIAN AIRLINES ENTERPRISE" : "Ethiopian",
    "CRISTALUX S.A (AMASZONAS URUGUAY)" : "Amaszonas Uruguay",
    "MAP TRANSPORTES AÉREOS LTDA." : "Map ",
    "DINAR LÍNEAS AEREAS" : "Dinar Líneas Aéreas",
    "AIRBRIDGE CARGO AIRLINES (VOLGA-DNEPR GROUP)" : "Airbridge Cargo",
    "BRUSSELS AIRLINES" : "Brussels Airlines",
    "EMPRESA DE TRANSPORTES AÉREOS DE CABO VERDE - TACV S.A." : "Cabo Verde Airlines",
    "TUI AIRLINES BELGIUM - JETAIRFLY" : "TUI Belgium",
    "FB LÍNEAS AÉREAS S.A (FLYBONDI)" : "FlyBondi",
    "AIR AUSTRAL" : "Air Austral",
    "ASTA LINHAS AÉREAS LTDA ( EX - AMÉRICA DO SUL LINHAS AÉREAS LTDA.)" : "Asta Linhas Aéreas",
    "COMPAÑIA DE AVIACION PARAGUAYA SOCIEDAD ANONIMA - PARANAIR (EX- AMASZONAS PARAGUAY)" : "Amaszonas Paraguay",
    "ICELANDAIR" : "Icelandair",
    "LAN ARGENTINA S.A." : "LATAM Argentina",
    "LAUDA AIR SPA" : "Lauda Air",
    "AZERBAIJAN AIRLINES" : "Azerbaijan Airlines",
    "ALL NIPPON AIRWAYS" : "ANA",
    "COMPAÑIA DE SERVICIOS DE TRANSPORTE AEREO AMASZONAS S/A." : "Amaszonas",
    "EASTERN AIRLINES" : "Eastern Airlines",
    "MEGA LINHAS AÉREAS LTDA." : "Mega Linhas Aéreas",
    "MODERN TRANSPORTE AÉREO DE CARGA S.A." : "Modern Logistics",
    "QANTAS AIRWAYS" : "Qantas",
    "NORWEGIAN AIR UK LIMITED" : "Norwegian",
    "OMNI TÁXI AÉREO S.A." : "Omni Taxi Aéreo",
    "LOT POLISH AIRLINES" : "LOT Polish Airlines",
    "PUMA AIR LINHAS AÉREAS LTDA." : "Puma Air",
    "RICO" : "Rico Linhas Aéreas",
    "SKY AIRLINES S.A." : "Sky Airline",
    "TRANSCARGA INTERNATIONAL AIRWAYS C.A." : "Transcarga International",
    "AIGLE AZUR" : "Aigle Azur",
    "RIO SUL" : "Rio Sul SAR",
    "TWO TÁXI AÉREO LTDA." : "Two Taxi Aéreo",
    "SKYMASTER" : "Skymaster Airlines",
    "JETSMART AIRLINES SPA - CHILE" : "Jetsmart",
    "TUI AIRWAYS LTD" : "TUI Airways",
    "TAF LINHAS AÉREAS S.A." : "TAF Linhas Aéreas",
    "FLY ALLWAYS N.V." : "Fly AllWays",
    "TAVAJ" : "TAVAJ",
    "MODERN TRANSPORTE AEREO DE CARGA S.A" : "Modern Logistics",
    "TRANSPORTES AEREOS PRESIDENTE S.A." : "Presidente Transportes Aéreos",
    "TRANS GUYANA AIRWAYS" : "Trans Guyana Airways",
    "SCANDINAVIAN AIRLINES SYSTEM" : "SAS"
}

ANAC_RENAME_COLUMNS = {
    "empresa (sigla)" : "airline_code",
    "empresa (nome)" : "airline_name",
    "empresa (nacionalidade)" : "airline_country",
    "ano" : "year",
    "mês" : "month",
    "aeroporto de origem (sigla)" : "airport_origin_code",
    "aeroporto de origem (nome)" : "airport_origin_name",
    "aeroporto de origem (uf)" : "airport_origin_state",
    "aeroporto de origem (região)" : "airport_origin_region",
    "aeroporto de origem (país)" : "airport_origin_country",
    "aeroporto de origem (continente)" : "airport_origin_continent",
    "aeroporto de destino (sigla)" : "airport_destination_code",
    "aeroporto de destino (nome)" : "airport_destination_name",
    "aeroporto de destino (uf)" : "airport_destination_state",
    "aeroporto de destino (região)" : "airport_destination_region",
    "aeroporto de destino (país)" : "airport_destination_country",
    "aeroporto de destino (continente)" : "airport_destination_continent",
    "natureza" : "flight_type",
    "grupo de voo" : "flight_frequency",
    "carga paga (kg)" : "payload_paid_kg",
    "carga grátis (kg)" : "payload_free_kg",
    "correio (kg)" : "payload_mail_kg",
    "ask" : "ask",
    "rpk" : "rpk",
    "atk" : "atk",
    "rtk" : "rtk",
    "combustível (litros)" : "fuel_l",
    "distância voada (km)" : "flight_distance_km",
    "decolagens" : "departures",
    "carga paga km" : "payload_paid_km",
    "carga gratis km" : "payload_free_km",
    "correio km" : "payload_mail_km",
    "assentos" : "seats",
    "payload" : "payload",
    "horas voadas" : "flight_hours",
    "bagagem (kg)" : "payload_baggage_kg",
    "passageiros pagos" : "passengers_paid",
    "passageiros grátis" : "passengers_free"
}

ESTADOS = {
    "Acre" : "AC'",
    "Alagoas" : "AL",
    "Amapá" : "AP",
    "Amazonas" : "AM",
    "Bahia" : "BA",
    "Ceará" : "CE",
    "Espírito Santo" : "ES",
    "Goiás" : "GO",
    "Maranhão" : "MA",
    "Mato Grosso" : "MT",
    "Mato Grosso do Sul " : "MS",
    "Minas Gerais" : "MG",
    "Pará" : "PA",
    "Paraíba" : "PB",
    "Paraná" : "PR",
    "Pernambuco" : "PE",
    "Piauí" : "PI",
    "Rio de Janeiro" : "RJ",
    "Rio Grande do Norte" : "RN",
    "Rio Grande do Sul " : "RS",
    "Rondônia" : "RO",
    "Roraima" : "RR",
    "Santa Catarina " : "SC",
    "São Paulo" : "SP",
    "Sergipe" : "SE",
    "Tocantins" : "TO",
    "Distrito Federal " : "DF"
}

ANAC_DROP_COLUMNS = [
    "aeroporto de origem (nome)",
    "aeroporto de origem (região)",
    "aeroporto de destino (nome)",
    "aeroporto de destino (região)",
    "natureza",
    "grupo de voo",
    "carga paga (kg)",
    "carga grátis (kg)",
    "correio (kg)",
    "combustível (litros)",
    "distância voada (km)",
    "carga paga km",
    "carga gratis km",
    "correio km",
    "payload",
    "horas voadas",
    "bagagem (kg)"]
